name: Deployment to AWS S3 with Docker/Python
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
        with:
          is-caching: "false"

      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache}}"

      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Load and cache dependencies
        uses: ./.github/actions/cache-deps

      - name: Test code
        id: run-tests
        run: npm run test

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v5
        with:
          name: test-report
          path: test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Load and cache dependencies
        uses: ./.github/actions/cache-deps

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist-files
          path: dist

  deploy:
    permissions:
      id-token: write
      contents: read
    needs: build
    environment: deploying
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Get build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
          path: ./dist

      - name: Output contents
        run: ls

      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::051180986309:role/GitHubDemo1
          aws-region: eu-central-1

      - name: Deploy site to S3
        id: s3deploy
        uses: ./.github/actions/deploy-s3-docker-python
        with:
          S3_BUCKET_NAME: gha-security-hostings-demos
          S3_REGION: eu-central-1
          DIST_FOLDER: ./dist

      - name: Output Information
        run: |
          echo "Live URL: ${{ steps.s3deploy.outputs.website-url }}"
